#!/bin/bash

##### bash aliases
alias atom="atom ./"
alias code="code ./"
# a better list all
alias ls="ls -a"
# show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
# hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
# update/reloat bash_profile
alias reload="source ~/.bash_profile"
# open current directory in finder
alias finder="open ."
# put computer to sleep
alias screensleep="pmset sleepnow"
# command used to bring iTerm to the forefront after long running tasks. For example, `yarn build ; remind`
alias remind="osascript -e 'tell application \"iTerm2\"' -e 'activate' -e 'display alert \"Done!\"' -e 'end tell'"
alias remindme="osascript -e 'tell application \"iTerm2\"' -e 'activate' -e 'display alert \"Done!\"' -e 'end tell'"

##### TODO bash_autocomplete

##### bash exports
export EDITOR="code"
export PATH="/usr/local/bin:$PATH"
# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# nvm config
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Make new shells by default use the version of node 
# declared in the current directory where the shell was opened.
nvm use &> /dev/null

# bash completion config
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

##### bash functions
weather() {
    city="$1"

    if [ -z "$city" ]; then
        city="Austin"
    fi

    eval "curl http://wttr.in/${city}"
}

waning() {
    echo -ne '🌕\r'
    sleep .1
    echo -ne '🌖\r'
    sleep .1
    echo -ne '🌗\r'
    sleep .1
    echo -ne '🌘\r'
    sleep .1
    echo -ne '🌑\r'
}

waxing() {
    echo -ne '🌑\r'
    sleep .1
    echo -ne '🌒\r'
    sleep .1
    echo -ne '🌓\r'
    sleep .1
    echo -ne '🌔\r'
    sleep .1
    echo -ne '🌕\r'
}

on() {
    # monitor backlight
    eval "curl --silent --insecure --request PUT --data '{\"on\":true,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/24/state > /dev/null"
    # desk
    eval "curl --silent --insecure --request PUT --data '{\"on\":true,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/19/state > /dev/null"
    # floor lamp
    eval "curl --silent --insecure --request PUT --data '{\"on\":true,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/20/state > /dev/null"
    eval "waxing"
}

off() {
    # monitor backlight
    eval "curl --silent --insecure --request PUT --data '{\"on\":false,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/24/state > /dev/null"
    # desk
    eval "curl --silent --insecure --request PUT --data '{\"on\":false,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/19/state > /dev/null"
    # floor lamp
    eval "curl --silent --insecure --request PUT --data '{\"on\":false,\"bri\":254,\"hue\":39392,\"sat\":13,\"ct\":230}' https://192.168.2.44/api/NRyWFZ7E5A-weAiCl98FTL2OERdKQHdcdipYUisW/lights/20/state > /dev/null"
    eval "waning"
}

bye() {
    eval "off"
    echo 👋
    eval "pmset sleepnow"
}

##### bash options
# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob


##### colors
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
MAGENTA="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"
GRAY="$(tput setaf 8)"
BOLD="$(tput bold)"
UNDERLINE="$(tput sgr 0 1)"
INVERT="$(tput sgr 1 0)"
NOCOLOR="$(tput sgr0)"


##### bash prompt
. "$HOME/.bash_prompt"

#bash.local - for local settings that shouldn't be under version control
